# Generated by Django 4.0.2 on 2022-02-15 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('deleted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('archived_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('deleted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('archived_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm_books.author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('deleted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('archived_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('deleted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('archived_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('line_item', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm_books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('deleted_timestamp', models.DateTimeField(blank=True, null=True)),
                ('archived_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_private', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookworm_books.author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
