version: '3.5'

services:
  postgres:
    image: postgres
    container_name: bookworm-postgres
    hostname: bookworm-postgres
    environment:
      POSTGRES_DB: bookworm
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: bookworm-pgadmin
    hostname: bookworm-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:5050"
    networks:
      - postgres
    restart: unless-stopped

  bookworm-elasticsearch:
    image: elasticsearch:7.4.0
    container_name: bookworm-elasticsearch
    hostname: bookworm-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  bookworm-kibana:
    image: kibana:7.4.0
    container_name: bookworm-kibana
    hostname: bookworm-kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
